# Generated by Django 4.1.5 on 2023-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="views", field=models.IntegerField(default=0),
        ),
    ]
