# Generated by Django 4.1.5 on 2023-01-28 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_views"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="date",),
        migrations.AddField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
