# Generated by Django 4.1.5 on 2023-02-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_date_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
    ]
