# Generated by Django 4.1.5 on 2023-02-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="images",),
    ]
